apiVersion: apps/v1

kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-05-18T00-05-36Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        - --config-dir
        - "/etc/minio/config"
        - --certs-dir
        - "/etc/minio/certs"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: pgben-minio-secrets
              key: access-key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgben-minio-secrets
              key: secret-key
        envFrom:
        - configMapRef:
            name: minio-config
        volumeMounts:
        - name: minio-data
          mountPath: /data
        - name: minio-config
          mountPath: /etc/minio/config
        - name: minio-certs
          mountPath: /etc/minio/certs
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: api
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: api
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
      - name: minio-config
        projected:
          sources:
          - configMap:
              name: minio-encryption-config
          - configMap:
              name: minio-audit-config
      - name: minio-certs
        secret:
          secretName: minio-tls
      initContainers:
      - name: set-bucket-policy
        image: minio/mc:RELEASE.2023-05-18T00-05-36Z
        command:
        - /bin/sh
        - -c
        - |
          /usr/bin/mc alias set myminio https://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD --api S3v4 && \
          /usr/bin/mc policy set none myminio/pgben-documents || true
        envFrom:
        - secretRef:
            name: pgben-minio-secrets
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
