version: '3.8'

services:
  # =============================================================================
  # MinIO - Object Storage
  # =============================================================================
  minio:
    image: minio/minio:latest
    container_name: pgben-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=pgben-documents,pgben-backups
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    networks:
      - pgben-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # =============================================================================
  # MinIO Client - Create Buckets
  # =============================================================================
  createbuckets:
    image: minio/mc:latest
    container_name: pgben-minio-createbuckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/pgben-documents;
      /usr/bin/mc mb myminio/pgben-backups;
      /usr/bin/mc policy set public myminio/pgben-documents;
      exit 0;
      "
    networks:
      - pgben-network

# =============================================================================
# Volumes
# =============================================================================
volumes:
  minio_data:
    driver: local

# =============================================================================
# Networks
# =============================================================================
networks:
  pgben-network:
    driver: bridge
    external: true