apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_INITDB_ARGS: "--data-checksums --encoding=UTF8 --locale=pt_BR.utf8"
  # Configurações básicas
  max_connections: "100"
  shared_buffers: "256MB"
  effective_cache_size: "768MB"
  maintenance_work_mem: "64MB"
  work_mem: "4MB"
  # Configurações de WAL
  wal_level: "replica"
  max_wal_size: "1GB"
  min_wal_size: "80MB"
  # Configurações de autovacuum
  autovacuum: "on"
  # Configurações de log
  log_destination: "stderr"
  logging_collector: "on"
  log_directory: "pg_log"
  log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
  log_rotation_age: "1d"
  log_rotation_size: "10MB"
  log_min_duration_statement: "1000"
  log_statement: "ddl"
  log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
