export enum EscolaridadeEnum {
   ANALFABETO = 'ANALFABETO',
   FUNDAMENTAL_INCOMPLETO = 'FUNDAMENTAL_INCOMPLETO',
   FUNDAMENTAL_COMPLETO = 'FUNDAMENTAL_COMPLETO',
   MEDIO_INCOMPLETO = 'MEDIO_INCOMPLETO',
   MEDIO_COMPLETO = 'MEDIO_COMPLETO',
   SUPERIOR_INCOMPLETO = 'SUPERIOR_INCOMPLETO',
   SUPERIOR_COMPLETO = 'SUPERIOR_COMPLETO',
   POS_GRADUACAO = 'POS_GRADUACAO',
 }