/**
 * Enum que define os possíveis status de uma solicitação de benefício
 */
export enum StatusSolicitacao {
  RASCUNHO = 'RASCUNHO',
  PENDENTE = 'PENDENTE',
  EM_ANALISE = 'EM_ANALISE',
  AGUARDANDO_DOCUMENTOS = 'AGUARDANDO_DOCUMENTOS',
  APROVADA = 'APROVADA',
  REPROVADA = 'REPROVADA',
  LIBERADA = 'LIBERADA',
  CANCELADA = 'CANCELADA',
  EM_PROCESSAMENTO = 'EM_PROCESSAMENTO',
  CONCLUIDA = 'CONCLUIDA',
  ARQUIVADA = 'ARQUIVADA',
  ABERTA = "ABERTA",
}
