apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: pgben
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alertas-pgben@natal.rn.gov.br'
      smtp_auth_username: 'alertas-pgben@natal.rn.gov.br'
      smtp_auth_password: '${SMTP_PASSWORD}'
      smtp_require_tls: true

    templates:
      - '/etc/alertmanager/template/*.tmpl'

    route:
      group_by: ['alertname', 'job', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'email-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'email-notifications'
        group_wait: 10s
        repeat_interval: 1h
      - match:
          severity: warning
        receiver: 'email-notifications'
        group_wait: 30s
        repeat_interval: 3h

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'equipe-ti@semtas.natal.rn.gov.br'
        send_resolved: true
        headers:
          subject: '[ALERTA PGBEN] {{ .GroupLabels.alertname }}'
        html: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Alerta PGBen</title>
            <style>
              body { font-family: Arial, sans-serif; }
              .alert { padding: 15px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }
              .critical { background-color: #f2dede; border-color: #ebccd1; color: #a94442; }
              .warning { background-color: #fcf8e3; border-color: #faebcc; color: #8a6d3b; }
              .info { background-color: #d9edf7; border-color: #bce8f1; color: #31708f; }
              .resolved { background-color: #dff0d8; border-color: #d6e9c6; color: #3c763d; }
              table { border-collapse: collapse; width: 100%; }
              th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
              th { background-color: #f2f2f2; }
            </style>
          </head>
          <body>
            <h2>Alerta PGBen</h2>
            
            <div class="alert {{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}{{ else }}resolved{{ end }}">
              <h3>{{ .GroupLabels.alertname }}</h3>
              <p><strong>Status:</strong> {{ .Status }}</p>
              <p><strong>Severidade:</strong> {{ .CommonLabels.severity }}</p>
            </div>
            
            <h3>Detalhes dos Alertas</h3>
            <table>
              <tr>
                <th>Alerta</th>
                <th>Descrição</th>
                <th>Início</th>
                <th>Duração</th>
              </tr>
              {{ range .Alerts }}
              <tr>
                <td>{{ .Labels.alertname }}</td>
                <td>{{ .Annotations.description }}</td>
                <td>{{ .StartsAt }}</td>
                <td>{{ if eq .Status "firing" }}{{ duration .StartsAt .EndsAt }}{{ else }}Resolvido{{ end }}</td>
              </tr>
              {{ end }}
            </table>
          </body>
          </html>

    - name: 'slack-notifications'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'
        channel: '#pgben-alertas'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alerta:* {{ .Annotations.summary }}
            *Descrição:* {{ .Annotations.description }}
            *Severidade:* {{ .Labels.severity }}
            *Início:* {{ .StartsAt }}
          {{ end }}

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'job']
