apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgben-backup-pvc
  namespace: pgben
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
