apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgben-server
  labels:
    app: pgben-server
    version: v1
spec:
  progressDeadlineSeconds: 900  # 15 minutos para permitir inicialização completa
  replicas: 3
  selector:
    matchLabels:
      app: pgben-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # Garante zero downtime durante updates
  template:
    metadata:
      labels:
        app: pgben-server
        version: v1
    spec:
      containers:
      - name: pgben-server
        image: pgben-server:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pgben-database-secrets
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: pgben-database-secrets
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pgben-database-secrets
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pgben-database-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pgben-database-secrets
              key: database
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pgben-api-secrets
              key: jwt_secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: pgben-api-secrets
              key: jwt_refresh_secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: pgben-api-secrets
              key: encryption_key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 60  # 10 minutos total para inicialização
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 60  # Após startup
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120  # Após readiness
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: pgben-server-service
  labels:
    app: pgben-server
spec:
  selector:
    app: pgben-server
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: pgben-database-secrets
type: Opaque
data:
  host: cG9zdGdyZXM=  # postgres
  port: NTQzMg==      # 5432
  username: cGdiZW4=  # pgben
  password: cGFzc3dvcmQ=  # password
  database: cGdiZW4=  # pgben
---
apiVersion: v1
kind: Secret
metadata:
  name: pgben-api-secrets
type: Opaque
data:
  jwt_secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=  # your-jwt-secret-here
  jwt_refresh_secret: eW91ci1qd3QtcmVmcmVzaC1zZWNyZXQtaGVyZQ==  # your-jwt-refresh-secret-here
  encryption_key: eW91ci1lbmNyeXB0aW9uLWtleS1oZXJl  # your-encryption-key-here