apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: pgben
data:
  grafana.ini: |
    [server]
    domain = pgben-monitoring.semtas.natal.rn.gov.br
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true

    [auth]
    disable_login_form = false
    
    [auth.basic]
    enabled = true
    
    [auth.proxy]
    enabled = false
    
    [analytics]
    check_for_updates = false
    
    [security]
    admin_user = admin
    admin_password = ${GRAFANA_ADMIN_PASSWORD}
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Editor
    
    [dashboards]
    min_refresh_interval = 5s
    
    [alerting]
    enabled = true
    
    [unified_alerting]
    enabled = true
    
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = alertas-pgben@natal.rn.gov.br
    password = ${SMTP_PASSWORD}
    from_address = alertas-pgben@natal.rn.gov.br
    from_name = Grafana PGBen
    
    [log]
    mode = console
    level = info
    
    [metrics]
    enabled = true
    
    [tracing]
    enabled = false
