{
 "title": "PGBen - Banco de Dados PostgreSQL",
 "tags": [
  "database",
  "postgresql"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Conexões ao Banco de Dados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{job=\"postgres-exporter\", datname=\"pgben\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Tempo de Execução de Consultas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time_seconds{job=\"postgres-exporter\",datname=\"pgben\"}[5m])/rate(pg_stat_statements_calls{job=\"postgres-exporter\",datname=\"pgben\"}[5m])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Transações por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{job=\"postgres-exporter\",datname=\"pgben\"}[5m])) + sum(rate(pg_stat_database_xact_rollback{job=\"postgres-exporter\",datname=\"pgben\"}[5m]))",
     "legendFormat": "Transações/s"
    }
   ]
  },
  {
   "title": "Tamanho do Banco de Dados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"postgres-exporter\",datname=\"pgben\"}",
     "legendFormat": "Tamanho"
    }
   ]
  },
  {
   "title": "Uso de Conexões",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=\"postgres-exporter\", datname=\"pgben\"}) / pg_settings_max_connections{job=\"postgres-exporter\"} * 100"
    }
   ]
  },
  {
   "title": "Taxa de Deadlocks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{job=\"postgres-exporter\", datname=\"pgben\"}[5m]) / (rate(pg_stat_database_xact_commit{job=\"postgres-exporter\", datname=\"pgben\"}[5m]) + rate(pg_stat_database_xact_rollback{job=\"postgres-exporter\", datname=\"pgben\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Top 10 Consultas Mais Frequentes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_calls{job=\"postgres-exporter\", datname=\"pgben\"}[5m]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}