apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-backup
  namespace: pgben
spec:
  schedule: "0 3 * * *"  # Todos os dias às 3h da manhã
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: minio-backup
            image: minio/mc:latest
            command:
            - /bin/sh
            - -c
            - |
              cp /scripts/minio-backup.sh /tmp/ && \
              chmod +x /tmp/minio-backup.sh && \
              /tmp/minio-backup.sh
            env:
            - name: PGBEN_MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: pgben-config
                  key: MINIO_HOST
            - name: PGBEN_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pgben-secrets
                  key: MINIO_ACCESS_KEY
            - name: PGBEN_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pgben-secrets
                  key: MINIO_SECRET_KEY
            - name: PGBEN_MINIO_BACKUP_DIR
              value: "/backup/minio"
            - name: PGBEN_RETENTION_DAYS
              value: "30"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
            - name: scripts-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: pgben-backup-pvc
          - name: scripts-volume
            configMap:
              name: pgben-backup-scripts
              defaultMode: 0755
