apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgben-server-pdb
  labels:
    app: pgben-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pgben-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgben-server
  labels:
    app: pgben-server
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgben-server-role
  labels:
    app: pgben-server
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgben-server-rolebinding
  labels:
    app: pgben-server
subjects:
- kind: ServiceAccount
  name: pgben-server
  namespace: default
roleRef:
  kind: Role
  name: pgben-server-role
  apiGroup: rbac.authorization.k8s.io