apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pgben
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:
      # Configuração para scrape do próprio Prometheus
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      # Configuração para scrape da API do PGBen
      - job_name: 'pgben-api'
        metrics_path: '/monitoring/metrics'
        scrape_interval: 10s
        static_configs:
        - targets: ['pgben-server:3000']
        
      # Configuração para scrape de métricas de segurança da API do PGBen
      - job_name: 'pgben-security-metrics'
        metrics_path: '/monitoring/metrics/security'
        scrape_interval: 30s
        static_configs:
        - targets: ['pgben-server:3000']
        
      # Configuração para scrape de métricas de documentos da API do PGBen
      - job_name: 'pgben-document-metrics'
        metrics_path: '/monitoring/metrics/documents'
        scrape_interval: 30s
        static_configs:
        - targets: ['pgben-server:3000']
        
      # Configuração para scrape de métricas de sistema da API do PGBen
      - job_name: 'pgben-system-metrics'
        metrics_path: '/monitoring/metrics/system'
        scrape_interval: 15s
        static_configs:
        - targets: ['pgben-server:3000']

      # Configuração para scrape do Node Exporter
      - job_name: 'node-exporter'
        static_configs:
        - targets: ['node-exporter:9100']

      # Configuração para scrape do PostgreSQL Exporter
      - job_name: 'postgres-exporter'
        static_configs:
        - targets: ['postgres-exporter:9187']

      # Configuração para scrape do MinIO
      - job_name: 'minio'
        metrics_path: '/minio/v2/metrics/cluster'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets: ['minio:9000']
