apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgben-server-metrics
  labels:
    app: pgben-server
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pgben-server
  endpoints:
  - port: http
    path: /api/v1/metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'go_.*'
      action: drop
    - sourceLabels: [__name__]
      regex: 'process_.*'
      action: drop
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: v1
kind: Service
metadata:
  name: pgben-server-metrics
  labels:
    app: pgben-server
    component: metrics
spec:
  selector:
    app: pgben-server
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP