apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: pgben
data:
  kibana.yml: |
    server.name: pgben-kibana
    server.host: "0.0.0.0"
    
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    elasticsearch.username: "${ELASTICSEARCH_USER:elastic}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD:changeme}"
    
    # Configurações de segurança
    xpack.security.enabled: true
    xpack.reporting.enabled: true
    xpack.monitoring.enabled: true
    
    # Configurações de interface
    i18n.locale: "pt-BR"
    
    # Configurações de logs
    logging.dest: stdout
    logging.json: true
    
    # Configurações de monitoramento
    monitoring.ui.container.elasticsearch.enabled: true
    
    # Configurações de alertas
    xpack.encryptedSavedObjects.encryptionKey: "${KIBANA_ENCRYPTION_KEY:pgben-kibana-key}"
