export enum ROLE {
  ADMIN = 'ADMIN',
  TECNICO_UNIDADE = 'TECNICO_UNIDADE',
  GESTOR_UNIDADE = 'GESTOR_UNIDADE',
  GESTOR_MUNICIPAL = 'GESTOR_MUNICIPAL',
  CIDADAO = 'CIDADAO'
}

export const ROLES_KEY = 'roles';
