apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-backup
  labels:
    app: pgben-backup
spec:
  schedule: "30 1 * * *"  # Executa diariamente às 01:30
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: minio-backup
            image: minio/mc:RELEASE.2023-05-18T00-05-36Z
            command:
            - /bin/bash
            - /scripts/minio-backup.sh
            env:
            - name: MINIO_ENDPOINT
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_BUCKET_NAME
              value: "pgben-documents"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pgben-minio-secrets
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pgben-minio-secrets
                  key: secret-key
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
            - name: backup-scripts
              mountPath: /scripts
            resources:
              requests:
                cpu: "150m"
                memory: "256Mi"
              limits:
                cpu: "300m"
                memory: "512Mi"
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          - name: backup-scripts
            configMap:
              name: backup-scripts-configmap
              defaultMode: 0755
